name: Build and publish images

on:
  schedule:
    - cron: "0 22 * * *"  # Every day at 22:00 (upstream builds at 19:20)
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  check:
    name: Pre-flight checks
    runs-on: ubuntu-latest

    steps:
      - name: Ensure upstream build is passing
        run: curl -s https://github.com/cgwalters/sync-fedora-ostree-containers/actions/workflows/build.yml/badge.svg | grep -q passing
        if: ${{ github.event_name == 'schedule' }}

  publish:
    name: Build and push images to container registry
    needs: check
    strategy:
      fail-fast: false
      matrix:
        version: [ 36, 37, rawhide ]
    uses: ./.github/workflows/publish.yml
    with:
      stable: true
      version: ${{ matrix.version }}
