name: Build and publish development images

on:
  push:
    branches:
      "testing"
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: read
  packages: write

jobs:
  publish:
    name: Build and push development image to container registry
    runs-on: ubuntu-latest
    timeout-minutes: 40
    strategy:
      fail-fast: false
      matrix:
        variant: [ silverblue, kinoite ]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup environment
        run: |
          echo "VERSION=37" >> $GITHUB_ENV
          echo "CONTAINERFILE=$(find src/ -type f -iname "${{ matrix.variant }}.containerfile")" >> $GITHUB_ENV

      - name: Build image
        id: build
        uses: redhat-actions/buildah-build@v2
        with:
          context: src/
          containerfiles: ${{ env.CONTAINERFILE }}
          build-args: FEDORA_VERSION=${{ env.VERSION }}
          image: ${{ matrix.variant }}
          tags: testing
          oci: true

      - name: Push to container registry
        id: push
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build.outputs.image }}
          tags: ${{ steps.build.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
